#!/bin/bash

curr_mac=$(ifconfig en0 | awk '/ether/{print $2}')

echo current MAC of this machine is $curr_mac

echo I am gonna generate a random hex value!

new_mac=$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//')

echo Random MAC generated is $new_mac

sudo ifconfig  en0 ether $new_mac

echo restarting the WiFi, turning off.

sudo ifconfig en0 down

sleep 4

sudo ifconfig en0 up

echo Verifying if back online

upd_mac=$(ifconfig en0 | awk '/ether/{print $2}')

echo updated MAC of this machine is $upd_mac
